// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSVaG30ijDwAZkj7WobSKrS-lmj1-r5PM',
    appId: '1:616155940286:web:3c5b2fe6f0fe7ae51365ef',
    messagingSenderId: '616155940286',
    projectId: 'vacua-app',
    authDomain: 'vacua-app.firebaseapp.com',
    storageBucket: 'vacua-app.appspot.com',
    measurementId: 'G-1TRTH1G17G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9fzn106p3tnmElsbq1ZxlD6DmrfQ6WU',
    appId: '1:616155940286:android:5a059084c8349f9e1365ef',
    messagingSenderId: '616155940286',
    projectId: 'vacua-app',
    storageBucket: 'vacua-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9xnxB8LTvgEBJEh1lMRO4xngh2aW2Os',
    appId: '1:616155940286:ios:3d8e45230b32242f1365ef',
    messagingSenderId: '616155940286',
    projectId: 'vacua-app',
    storageBucket: 'vacua-app.appspot.com',
    iosClientId: '616155940286-pbmapovu32f00m2v2g3kfi0jrta42roo.apps.googleusercontent.com',
    iosBundleId: 'com.example.vacuaApp',
  );
}
